# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Change Directory to src/TarkovHelper.API
      run: cd src/TarkovHelper.API
    - name: Show Dir
      run: pwd
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/TarkovHelper.API
    - name: Build
      run: dotnet build --no-restore
      working-directory: src/TarkovHelper.API
    - name: Unit Test
      run: dotnet test
      working-directory: tests/TarkovHelper.Tests
    - name: End To End Test
      run: dotnet test
      working-directory: tests/TarkovHelper.EndToEnd

